services:
  - type: web
    name: back2health-website
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: back2health-db
          property: connectionString
      - key: RESEND_API_KEY
        sync: false
    domains:
      - back2health.onrender.com

databases:
  - name: back2health-db
    databaseName: back2health
    user: back2health_user
    plan: starter